### ISSUE TITLE
Prometheus Integration

### ISSUE THREAD

**Issue by tomchavakis** [jaegertracing/jaeger-client-csharp#115]
At the https://www.jaegertracing.io/docs/1.8/client-features/ link the Prometheus integration is uknown.
I haven't find anything to the library documentation. 
Is there any implementation for this feature ?

**Comment by Falco20019** [comment]
Not implemented so far but I am interested in having it myself. So if no one implements it soon, I will do it as soon as I need it (next 4-6 months).

**Comment by Falco20019** [comment]
I will look into implementing it right now.

**Comment by Falco20019** [comment]
I want to wait for #116 to be merged before bringing this in. But I made some first tests at [the branch Falco20019/prometheus](https://github.com/jaegertracing/jaeger-client-csharp/tree/Falco20019/prometheus) and it seems to work as expected. Documentation also has to be updated a bit more then, but you basically would just have to use it as explained [here](https://github.com/jaegertracing/jaeger-client-csharp/blob/67ea8dca71571c164ebe163323de9d1ebf14c515/src/Jaeger.Prometheus/README.md).

I think if I should add some calls to simplify setting up the HTTP endpoint or pushing of metrics to a gateway, but since always depends on the application, it may be better just to document it (as in the link above) and leave it up to the user without wrapping it.

**Comment by Falco20019** [comment]
We should consider https://github.com/jaegertracing/jaeger/issues/161

**Comment by markusstephanides** [comment]
Hi, any updates on the Prometheus integration?

**Comment by Falco20019** [comment]
Not actively working on it. Would be great to get some feedback what metrics you would be interested in. Are those offered currently enough? Are you missing some? Please have a look at https://github.com/jaegertracing/jaeger-client-csharp/blob/master/src/Jaeger.Core/Metrics/MetricsImpl.cs
