### ISSUE TITLE
Configure LogLevel

### ISSUE THREAD

**Issue by Marusyk** [jaegertracing/jaeger-client-csharp#147]
Let's say I have the following appsettings:

```json
{
  "Serilog": {
    "MinimumLevel": {
      "Default": "Error",
      "Override": {
        "Microsoft": "Error",
        "System": "Error"
      }
    }
  }
}
```

Then my configuration:

```csharp
services.AddOpenTracing();
services.AddSingleton<ITracer>(sp =>
{
	var loggerFactory = sp.GetRequiredService<ILoggerFactory>();

	var reporter = new RemoteReporter.Builder()
		.WithSender(new UdpSender(options.UdpHost, options.UdpPort, options.MaxPacketSize))
		.WithLoggerFactory(loggerFactory)
		.Build();

	var sampler = GetSampler(options);

	var tracer = new Tracer
			.Builder(options.ServiceName)
		.WithReporter(reporter)
		.WithSampler(sampler)
		.Build();

	GlobalTracer.Register(tracer);

	return tracer;
});
```
I have specified minimum log level to Error. But at the end I got many other logs. How can I configure that?
![Screenshot_1](https://user-images.githubusercontent.com/9221694/57651578-35f1c900-75d6-11e9-9648-bdec9ad04b7d.png)

Actually I need only error logs (or maybe warnings too) but I got a lot of logs that I do not need. When I use Serilog it don't write any custom logs.

**Comment by Falco20019** [comment]
I assume this should be the same problem as in #146 that you mixed up the order of registering the Singleton and calling services.AddOpenTracing();

**Comment by Falco20019** [comment]
I had a look at your [example](https://github.com/Marusyk/JaegerSerilog). All the logs that you mention belong to `OpenTracing.Contrib.NetCore` and are not related to `ILogger` or even `Jaeger` itself. They are created for you, because you enabled them by calling `services.AddOpenTracing()`. So your request at https://github.com/opentracing-contrib/csharp-netcore/issues/42 is the correct place.
