### ISSUE TITLE
OpenTelemetry support

### ISSUE THREAD

**Issue by AlexeiScherbakov** [jaegertracing/jaeger-client-csharp#148]
OpenMetrics and OpenCensus merging into OpenTelemetry(https://github.com/open-telemetry)
When it will be implemented in jaeger client library for .NET?

**Comment by yurishkuro** [comment]
Does this help?

https://medium.com/jaegertracing/jaeger-and-opentelemetry-1846f701d9f2

**Comment by AlexeiScherbakov** [comment]
Yes, I already read this. So more accurate question. For current (now+1 year) development, if collector will be Jaeger, what set of libraries should be used: OpenMetrics or OpenTelemetry? Today we planning to replace zipkin with jaeger.

**Comment by yurishkuro** [comment]
I assume you mean s/OpenMetrics/OpenTracing/.

At the moment, OpenTelemetry is not in a state where you can start using it, so OpenTracing (or OpenCensus) are your only options. That should have little impact on which tracing backend you want to use, since they will all support Jaeger. However, you want to pay attention to which trace context format you want to use, if you're in a green field - I would recommend https://github.com/w3c/trace-context, but it's currently not implemented in Jaeger libs.
