### ISSUE TITLE
CI choice

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-csharp#15]
I noticed this repo uses AppVeyor for CI - is this just a preference or a convention for .Net projects (e.g. travis.org is not an option)?

**Comment by cwe1ss** [comment]
@yurishkuro: Most .NET projects use AppVeyor because they use Windows machines and they have a very nice integration with .NET's package manager NuGet. 

Building on Windows machines is still required if the project targets the full .NET framework (which this project currently does not - it targets the platform-independent ".NET Standard") or if it runs tests against the full .NET framework (which this project should probably do at some point). 

So ideally any modern .NET project should use both CI systems to build & test on Windows, Linux and OSX. (Of course only until one of the CI systems offers all of these platforms).

**Comment by grounded042** [comment]
We originally used AppVeyor as that's what we've used for other C# open source projects. But, I'm not opposed to using another system - especially if when the move to Jaeger org happens you guys want to use something different.

**Comment by yurishkuro** [comment]
The README needs a fix, as its [Build|Passing] icon points to the old name.

**Comment by cwe1ss** [comment]
@yurishkuro Can you add this project to the jaegertracing Travis account? I'll add a .travis.yml file.

As mentioned before, we would also need AppVeyor to build on Windows. There's certain features that are not possible on Linux. While we do not require any build-time features right now, we might very well need them soon (e.g. signing assemblies or targeting a specific version of the full .NET framework)

As we need the same for opentracing-csharp, I've written a how-to for setting up AppVeyor here: https://github.com/opentracing/opentracing-csharp/pull/82#issuecomment-376537504
The same should apply for jaegertracing as well.

**Comment by yurishkuro** [comment]
@cwe1ss I made you an admin on this repo, so you should be able to manage CI, definitely Travis, not sure about appveyor. Might be faster than me being a proxy.

Could you elaborate why we need both?

**Comment by yurishkuro** [comment]
Odd, when I synced my account on AppVeyor with GitHub, it created the project under my personal name https://ci.appveyor.com/project/yurishkuro/jaeger-client-csharp-5uj7p

@grounded042 do you know a better way to create a project so it looks like https://ci.appveyor.com/project/jaegertracing/jaeger-client-csharp ?

**Comment by grounded042** [comment]
@yurishkuro welcome to AppVeyor. The way they do user auth is super confusing and I think that you have to select the jaegertracing org when you sign in for it to appear where you want. I've run into the exact same problem that you have.

**Comment by grounded042** [comment]
@yurishkuro for instance when I sign into AppVeyor via Github I actually have to select `chatham` from the account dropdown and not `grounded042` to see https://ci.appveyor.com/project/chatham/letstrace. I think you have to be an admin or owner in an org to be able to sign in using the org.

Also, I don't think we need AppVeyor right now. To release something right now we can use Travis CI as the entire build process for the library works on Linux. However, if down the road we need/want to support something in the build process that only works on a Windows machine we will have to use AppVeyor.

**Comment by MikeGoldsmith** [comment]
@yurishkuro when you enable a repo in AppVeyor you nee to select it from correct org (each org you're a member of shows it's available repositories). That will ensure you get `{org}/{project}`, I've accidentally picked a fork of the official repository many times.

On the CI front, as discussed above, AppVeyor was the defacto choice because until .NET core you could only build on Windows reliably. Now with .NET Core other CI systems are available but if you target a non-core framework (eg .NET full 4.5), you still need a Windows host. I've seen plenty of projects use multiple CI platforms to ensure build process and then rely on AppVeyor directly for packaging / distribution of artefacts.

**Comment by yurishkuro** [comment]
I picked it like this:

![image](https://user-images.githubusercontent.com/3523016/38258419-68f24144-3730-11e8-97d3-51055c2f40a2.png)

I am guessing I also need to be on the org **account**, but I don't know how that can be achieved - does it need a separate login & password?  I don't have any other accounts in the profile dropdown.

![image](https://user-images.githubusercontent.com/3523016/38258488-9ba69590-3730-11e8-8a97-11b6414e7682.png)

**Comment by MikeGoldsmith** [comment]
What you have looks correct. Not sure why it's not working as expected. AppVeyor's support is normally pretty good, even on free accounts - [forum](https://help.appveyor.com/) / [email](mailto:team@appveyor.com)

**Comment by yurishkuro** [comment]
Just read a few of their support issues on forum, the github org support is not there. I don't want to waste time on this so I just renamed my account to jaegertracing and now the project name is good: https://ci.appveyor.com/project/jaegertracing/jaeger-client-csharp

Since I am logging in with github, I don't have to manage an extra password, so it's good enough. And I can add other collaborators to that account.
