### ISSUE TITLE
Lost Spans on Tracer Dispose

### ISSUE THREAD

**Issue by phxnsharp** [jaegertracing/jaeger-client-csharp#181]
## Requirement - what kind of business use case are you trying to solve?

Instrumenting a Managed C++ application with Jaeger using jaeger-client-csharp. The application is a short-lived process that is often run multiple times in parallel to solve portions of a larger problem.

## Problem - what in Jaeger blocks you from solving the requirement?

Even when Tracer.Dispose is properly called, spans that happen right at the end are intermittently lost.

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Dispose should reliably wait up until the timeout for spans to publish.

## Any open questions to address

See this proposed change to InMemorySender. It should have no effect on any of the tests, but instead it causes RemoteReporterTests.TestRemoteReporterFlushesOnClose to intermittently fail in a couple of different ways.  

https://github.com/phxnsharp/jaeger-client-csharp/commit/a5256d505dd830be477c5444af387495ef2e8619

**Comment by phxnsharp** [comment]
Interestingly, with the proposed change if you set RemoteReporterTests._closeTimeout to longer, it doesn't change the failures. It only takes longer to fail. This indicates to me that there is some type of deadlock happening during shutdown.

**Comment by Falco20019** [comment]
If `ProcessQueueLoop` and `FlushLoop` are properly written asynchronous functions, we wouldn't even need to call `Task.Factory.StartNew` on them, as this really only should be used with synchronous calls. We should try to make sure, that we don't call long-blocking synchronous code and use async all the way through. This way, `Task.Run` (which uses the thread pool) instead of `Task.Factory.StartNew` (which uses a real thread) would be the better option.
