### ISSUE TITLE
Add *.proto files to the repo

### ISSUE THREAD

**Issue by rparvizian-rbx** [jaegertracing/jaeger-client-csharp#192]
Could you please add the *.proto files for the jaeger tracer to the repo.
I'm trying to create a proxy, but I need the *.proto files that the jaeger tracer uses.

**Comment by yurishkuro** [comment]
proto files are in https://github.com/jaegertracing/jaeger-idl repo

**Comment by Falco20019** [comment]
@rparvizian-rbx To not having to compile them yourself (in case you do the proxy in C#), just use the NuGet package `Jaeger.Communication.Grpc`. This is generated from the protos and only includes gRPC and the generated protobuf files. No more logic. If you need another language, take the protos from where @yurishkuro has pointed you. Generating C# yourself is no fun due to the gogoproto dependencies.
