### ISSUE TITLE
4.3 release not available in Nuget

### ISSUE THREAD

**Issue by smitcham** [jaegertracing/jaeger-client-csharp#208]
I see that there's a 4.3 release from Feb 25, but this hasn't been updated in the Nuget package repository.  We've got a set of services that have updated to 4.3 Jaeger that are failing and I'm going to have to take several days to downgrade things because of missing methods.

**Comment by Falco20019** [comment]
I just checked and it‘s definetly on NuGET. There are only two packages on 0.3.7 which are the deprecated Thrift ones. These should not have been referenced directly, only through `Jaeger`. What is your setup? If you use Thrift, just make sure to add `Jaeger` without any other dependencies. These will always be included automatically.

![165FBB4A-12A4-4C2D-B9A3-3D60788FF306](https://user-images.githubusercontent.com/940619/113744136-b6f36580-9704-11eb-8caf-2b4dba1c2773.png)
![7FA40358-5883-4986-A19E-12D158182D21](https://user-images.githubusercontent.com/940619/113744141-b955bf80-9704-11eb-95a0-3d90ab2f5aa6.png)

**Comment by smitcham** [comment]
![image](https://user-images.githubusercontent.com/82305/113781997-206c7780-96f7-11eb-91b1-41f468376274.png)
this is the one that is missing.   However, the inclusion of this package in our downstream projects was an artifact of references not getting cleaned up correctly, since the 4.3 packages don't reference it anymore.

**Comment by Falco20019** [comment]
Glad that you figured it out :) We were able to finally use the official `ApacheThrift` package since `0.4.0` and therefore stopped vendoring it ourselves. This should also make it easier in the future and reduce name conflicts.

We also decided with that version to split senders and communication up and to make the core package agnostic. This also allowed only having gRPC as communication without any reference onto Thrift.

The communication packages only contain the pre-generated IDLs with the according dependencies and can be used by everyone. No real dependency on Jaeger there.

The sender packages use the communication packages and add the logic to plug it into Jaeger. This reduces the dependencies, especially in the case of custom senders.
