### ISSUE TITLE
TypeLoadException when using latest version of Apache Thrift (0.14.1)

### ISSUE THREAD

**Issue by object** [jaegertracing/jaeger-client-csharp#211]
## Requirement - what kind of business use case are you trying to solve?

Using distributed tracing with Jaeger and UDP sender in .NET 5.0 application

## Problem - what in Jaeger blocks you from solving the requirement?

A minimal console app written in C# works fine as long as ApacheThrift version 0.13.x or earlier is used. Recently Thrift was updated, and if I reference version 0.14.x (I tested specifically 0.14.1), then the application crashes with the following exception:

> System.TypeLoadException: Method 'get_Configuration' in type 'Jaeger.Thrift.Senders.Internal.ThriftUdpClientTransport' from assembly 'Jaeger.Communication.Thrift, Version=1.0.0.0, Culture=neutral, PublicKeyToken=9516061555a213a8' does not have an implementation.
>    at Jaeger.Senders.Thrift.UdpSender..ctor(String host, Int32 port, Int32 maxPacketSize)
> 

The sample application code:

```
using Jaeger;
using Jaeger.Senders.Thrift;
using Microsoft.Extensions.Logging;
namespace JaegerClient
{
    class Program
    {
        static void Main(string[] args)
        {
            var loggerFactory = new LoggerFactory();
            var senderConfiguration = new Configuration.SenderConfiguration(loggerFactory)
                .WithSender(new UdpSender());
            var reporterConfiguration = new Configuration.ReporterConfiguration(loggerFactory)
                .WithSender(senderConfiguration);
            var tracer = (Tracer)new Configuration("new-service", loggerFactory)
                .WithReporter(reporterConfiguration)
                .GetTracer();
            using (var scope = tracer.BuildSpan("foo").StartActive(true))
            {
                System.Threading.Thread.Sleep(1000);
            }
            tracer.Dispose();
        }
    }
}

```

## Proposal - what do you suggest to solve the problem or improve the existing situation?

Downgrading ApacheThrift library to 0.13.0.1 fixes the problem.

**Comment by Falco20019** [comment]
Looks like the Thrift team broke with the public API. Since it’s a 0.x version, there is officially no enforced forwards compatibility. We can check if it‘s possible to get it working again or if it‘s possible to have a workaround. If not, we might just need to update and fix it for latest version usage.

**Comment by Falco20019** [comment]
I rechecked what `ApacheThrift` changed, and the changes were pretty big (see https://github.com/apache/thrift/blob/0.14.1/CHANGES.md). Usually, Apache only offers upgrade inside of one 0.x version range. And the thrift files have to be generated using a matching version. So it's not easy to just update the reference in your project, since it will most probably break the generated code.

#213 will update the dependency since it's also fixing a problem with .NET Framework usage.

Feel free to try it out using the artifacts from here (using a local nuget repo): https://ci.appveyor.com/project/jaegertracing/jaeger-client-csharp/builds/39350102/artifacts
