### ISSUE TITLE
The type or namespace name 'Thrift' does not exist in the namespace 'Jaeger.Senders'

### ISSUE THREAD

**Issue by justinTM** [jaegertracing/jaeger-client-csharp#220]
**Describe the bug**
`Jaeger.Example.WebApi/Startup.cs(4,22): error CS0234: The type or namespace name 'Thrift' does not exist in the namespace 'Jaeger.Senders' (are you missing an assembly reference?)`

**To Reproduce**
1. clone repo locally
2. navigate to examples/Jaeger.Example.WebApi
3. run `dotnet run`
4. receive error `CSC : error CS8102: Public signing was specified and requires a public key, but no public key was specified. [aeger-client-csharp/examples/Jaeger.Example.WebApi/Jaeger.Example.WebApi.csproj]`
5. replace relative path package reference with Nuget package reference as described in the comment on lines 10-14 in Jaeger.Example.WebApi.csproj
6. receive error `Jaeger.Example.WebApi/Startup.cs(4,22): error CS0234: The type or namespace name 'Thrift' does not exist in the namespace 'Jaeger.Senders' (are you missing an assembly reference?)`

**Expected behavior**
The app runs.

**Screenshots**

**Version (please complete the following information):**
 - OS: macOS
 - Jaeger version: [e.g. 1.8]
 - Deployment: [e.g. bare metal, Docker, Kubernetes, ...]

**What troubleshooting steps did you try?**
Try to follow https://www.jaegertracing.io/docs/latest/troubleshooting/ and describe how far you were able to progress and/or which steps did not work.

**Additional context**

**Comment by Falco20019** [comment]
Hi @justinTM,

Thanks for your report. Have your tried updating the NuGet references? They seem pretty old. Jaeger is at 1.0.2 and OpenTracing at 0.7.1 now.

Most people use the example at https://github.com/opentracing-contrib/csharp-netcore to get started with the Web usage. But since we have the example in here, it should at least work. Sorry for the inconvenience. I will look into it and fix it.

**Comment by Falco20019** [comment]
@justinTM I just tried it locally using your steps provided. I don't get the message in step 4 and when using the `ProjectReference` (without adjusting the `csproj`) OR when using version `1.0.2` of `Jaeger`, it works flawlessly. I will update the `csproj` to contain the latest versions.

Can you check if the message in step 4 is also appearing when using the latest version? Are you also sure that you have checked out `master`? Because `Jaeger.Example.WebApi/Startup.cs(4,22)` should be line 3 and not line 4 in the current code base.

**Comment by Falco20019** [comment]
Please re-open if this did not solve your issue.

**Comment by justinTM** [comment]
so I deleted and re-cloned, cd'd into `examples/Jaeger.Example.WebApi`, then ran `dotnet run`... same error as in step 4 ("CSC : error CS8102: Public signing was specified and requires a public key, but no public key was specified.")

**Comment by Falco20019** [comment]
Are you sure you cloned master? It's neither happening on my machine nor on the build server.

Maybe you have a Directory.Builds.props (or target) file anywhere above in your folder structure up to root where you checked it out defining that requirement? Those files are all processed by the build chain. So maybe try cloning it into a clean environment (separate folder like root) if you are not sure.

**Comment by justinTM** [comment]
I think I figured it out. I had dotnet sdk 5. here's what I ran to get 3.1:
```shell
brew uninstall dotnet
brew tap isen-ng/dotnet-sdk-versions
brew install --cask dotnet-sdk3-1-400
brew install --cask dotnet
dotnet --list-sdks
```

**Comment by Falco20019** [comment]
Still strange, since I'm also using the .NET SDK 5.0 on Windows without issues. Maybe that's a macOS thing, but it should behave similar on all platforms since all are maintained by Microsoft and not third parties.
