### ISSUE TITLE
Support Byte-Code-Injection in Net Or NetCore?

### ISSUE THREAD

**Issue by DevWithLin** [jaegertracing/jaeger-client-csharp#64]
just like skywalking java agent or pinpoint java agent,which was supporting byte-code-injection.
so jaeger-client-csharp is supporting in net core?

**Comment by yurishkuro** [comment]
This is the main reason the OpenTracing project was created. The instrumentation, either explicit or based on byte-code manipulation, does not need to be tied to the tracing backend or a tracing library being used. We as an industry need to stop redoing the same instrumentation work over and over. Jaeger libraries implement the OpenTracing API, nothing more. If there is existing instrumentation that uses OpenTracing API, Jaeger libraries can be plugged into that. But Jaeger libraries do not do instrumentation themselves.

I am not familiar with the details skywalking or pinpoint agents. One would hope that if they are spending all this effort on building & maintaining byte-code instrumentation they would do make it OpenTracing compatible so that it's portable rather than locked-in to a specific tracing backend.

Case in point: https://github.com/uber-common/opentracing-python-instrumentation. This library is conceptually similar to byte code instrumentation because it uses monkey-patching. This library can work with any OpenTracing compatible tracer, including Jaeger.

**Comment by yurishkuro** [comment]
there was an initial attempt to build an OpenTracing agent for auto-instrumentation, but I don't think it has been maintained since then: https://github.com/opentracing-contrib/java-agent

**Comment by DevWithLin** [comment]
en, because i  have no idea that net core auto-instrumentation implement.which is  first issue import point. i just be curious net core implement. i thought jaeger-client-csharp already implemet. 
[appdynamic answer](https://community.appdynamics.com/t5/NET-Agent-Installation/Byte-Code-Injection/td-p/30656).
[Profiling Overview](https://docs.microsoft.com/zh-cn/dotnet/framework/unmanaged-api/profiling/profiling-overview)

**Comment by cwe1ss** [comment]
If you're on .NET Core you could use https://github.com/opentracing-contrib/csharp-netcore - it automatically adds OpenTracing-compatible instrumentation for outgoing HTTP calls, Entity Framework calls, ASP.NET Core requests etc.

Our example already uses that library - see here: https://github.com/jaegertracing/jaeger-client-csharp/blob/239251ada6168960b7dd5abdd135dbe26412bd11/examples/Jaeger.Example.WebApi/Startup.cs#L28

**Comment by yurishkuro** [comment]
@cwe1ss would be awesome to have a small blog post about this instrumentation and the example under https://medium.com/jaegertracing
