### ISSUE TITLE
Separation of TraceId and SpanId

### ISSUE THREAD

**Issue by Falco20019** [jaegertracing/jaeger-client-csharp#75]
The follow-up discussion from [here](https://github.com/jaegertracing/jaeger-client-csharp/pull/55#issue-182303816).

The open questions are:
* Do we want to keep `TraceId` and `SpanId` separate? 
* Do we want to stay close to Java in this case?

I like the separation more than the Java implementation. As of now, `jaeger-client-java` only supports 64bit `TraceId`s. We also default to 64bit and are also completely compatable but still keep the flexibility.

**Comment by yurishkuro** [comment]
I assume the question is about _types_, not _values_. In Go we have separate `TraceID` and `SpanID` types, but the former is a two-field by-value struct and the latter is an alias to uint64 (so also by-value), so that both are embedded into the `SpanContext` struct without requiring memory allocations. Don't know how much overhead memory allocations and gc add in C#. I suspect once we add 128bit ID support to Java we'd still stick with long fields in the Span object directly, to minimize unnecessary allocations.

**Comment by yurishkuro** [comment]
then yay for types

**Comment by Falco20019** [comment]
I leave it open for a couple more days, in case someone else wants to share his opinion.
