### ISSUE TITLE
Dependency on Thrift

### ISSUE THREAD

**Issue by Falco20019** [jaegertracing/jaeger-client-csharp#76]
The follow-up discussion from [here](https://github.com/jaegertracing/jaeger-client-csharp/pull/55#issuecomment-382172354).

The open questions are:
* Do we want to keep our dependency on `Thrift`?

Java thinks about modularization and using `Configuration` and `service load pattern` to only load what's needed. We would have to analyze how to do this in C#. I assume it would be similar to how `Microsoft.Extensions.Logging` and `ASP.NET Core` are abstracting everything into packages and enabling it though adding a middleware/provider and calling an extension method on `Configuration` presumably.

**Comment by animusblue** [comment]
I'm currently having an issue with using this library because of the dependency on the Jaeger.Thrift.VendoredThrift package. It seems that the Jaeger.Thrift.VendoredThrift is a custom copy that doesn't have the asp.net core references. This is causing an issue with our own thrift library as both the nuget package and the default implementation (through a submodule referencing the thrift master) are using the same Thrift namespace. Since Jaeger.Thrift.VendoredThrift isn't a standard copy we can't switch to using it (we need the http protocol). Should the nuget package be placed under it's own namespace to prevent direct conflicts with the master thrift library?

**Comment by Falco20019** [comment]
#116 also has problems with Thrift. Is there finally an up2date nuget package of Thrift? A year ago we only did a request at the issue tracker to finally update it.

**Comment by animusblue** [comment]
We've only found 3rd party NuGet packages and most of them were out of date. We're hesitant to rely on non-official sources for something like this which is why we're using a submodule.

**Comment by Falco20019** [comment]
There finally are official packages available for Thrift at https://www.nuget.org/packages/ApacheThrift/
