### ISSUE TITLE
Create crossdock integration tests

### ISSUE THREAD

**Issue by yurishkuro** [jaegertracing/jaeger-client-csharp#85]
To address issues like https://github.com/jaegertracing/jaeger-client-csharp/issues/80#issuecomment-394416348

**Comment by Falco20019** [comment]
It's a hard problem on Appveyor. Right now, we are using Windows Server 2016 build environment to build everything. Sadly, Appveyor does not support running Docker Containers for Linux on those machines. There seems to be an option if you buy nested virtualization but that's also a bit quirky...

They also work on a solution based on Windows Server 2019 and Docker EE which would allow using Windows + Linux containers. But as it looks now, the best option would be to just switch to an Ubuntu environment for our Builds since we are not really depending on using Windows right now AFAIK. But this will definetly take some more time.
